version: '3.7'

services:

  cartly-db:
    image: postgres:16.2-alpine3.19  
    container_name: cartly-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:      
      - 'db:/var/lib/postgresql/data'
    networks:
      - cartly

  cartly-api:
    depends_on:
      - cartly-db
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@cartly-db:5432/${POSTGRES_DB}
      - NODE_ENV=${NODE_ENV}
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: cartly-api
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    networks:
      - cartly

networks:
  cartly:
    driver: bridge

volumes:
  db: