version: '3'
services:
  cartly-api:
    environment:
      NODE_ENV: development
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: cartly-api
    volumes:
      - ./:/usr/src/app
    expose:
      - '3000'
    ports:
      - "3000:3000"
    command: npm run dev